"""empty message

Revision ID: cd9d5e495fea
Revises: 133980f8d61d
Create Date: 2023-03-18 01:30:49.178035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9d5e495fea'
down_revision = '133980f8d61d'
branch_labels = None
depends_on = None


def upgrade():
    pass



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('credits')

    # ### end Alembic commands ###
